---
title: "HW5"
author: "Victoria Talbott"
date: "2024-11-17"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE, message = FALSE)
```

#### Load Libraries

```{r}
# laod Libraries
library(tidyverse)
library(ggplot2)
library(readr)
library(lubridate)
```

### Read in data

```{r}
#read in data
homicides <- read_csv("../data/homicide-data.csv")
```


### Tidy data
Preparing data for the final graph that shows homicides per month over the years. 
```{r}
## clean data
# make a new column called city_name that combines city and state for something like this "Baltimore, MD)
homicides <- homicides %>% 
  mutate(city_name = paste(city, state, sep = ", ")) 
#select columns
homicides <- homicides %>% 
  select(reported_date, city, state, disposition, city_name)
#lubridate
homicides <- homicides %>% 
  mutate(date_reported = ymd(reported_date)) %>% 
  select(-reported_date)

#group by month and year then sum up how many homicides their were
homicide_count <- homicides %>% 
  mutate(year = year(date_reported),        
         month = month(date_reported, label = FALSE)) %>%  
  group_by(year, month, city_name) %>% #grouping data for further analysis
  summarise(n = n())  
#filter down to Baltimore
homicide_count <- homicide_count %>% 
  filter(city_name == "Baltimore, MD")

# add column for summer vs winter
# 11, 12, 1, 2, 3, 4 (winter all other numbers are summer)
homicide_count <- homicide_count %>% 
  mutate(
    season = ifelse(month %in% c(11, 12, 1, 2, 3, 4), "winter", "summer"))


```

## Homicides by month from 2007 to 2017 in Baltimore, MD
```{r}
# graph for homicides by month from 2007 to 2017 for Baltimore, MD

homicide_count %>% 
  ggplot(aes(x = date))
```





